background            #000000
foreground            #ffffff
cursor                #00ff00
selection_background  #fffd8c

background_opacity 1
background_blur 0
allow_remote_control yes
listen_on unix:/tmp/kitty
enabled_layouts splits
enable_audio_bell no

#black
color0 #000000
color8 #000000

#red
color1 #ff0000
color9 #ff0000

#green
color2 #00ff00
color10 #00ff00

#yellow
color3 #ffff00
color11 #ffff00

#cyan
color4 #00ffff
color12 #00ffff

#magenta
color5 #ff00ff
color13 #ff00ff

#blue
color6 #0000ff
color14 #0000ff

#white
color7 #ffffff
color15 #ffffff

selection_foreground #000000

