wallpaper {
    monitor = eDP-1
    path = ~/Pictures/wallpapers/abstract/11.jpg
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-1
    path =  ~/Pictures/wallpapers/abstract/11.jpg
    fit_mode = cover
}

splash = false
